apiVersion: v2
name: hello-chart
description: A Helm chart for Kubernetes

type: application

version: 0.2.0
appVersion: v3

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database

