replicaCount: 2
 
image:
  repository: dharlequin/go-rest-crud
 
service:
  type: NodePort
  port: 9000
 
postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
