apiVersion: v1
kind: Secret
metadata:
  name: hello-secret-go
type: Opaque
data:
  DB_HOST: {{(include "postgresql.fullname" .)  | b64enc | quote}}
  DB_USER: {{.Values.postgresql.postgresqlUsername  | b64enc | quote}}
  DB_PASSWORD: {{.Values.postgresql.postgresqlPassword  | b64enc | quote}}
  DB_NAME: {{.Values.postgresql.postgresqlDatabase  | b64enc | quote}}
  DB_PORT: {{.Values.postgresql.service.port  | b64enc | quote}}
